import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { UserProvider } from "@/context/usercontext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NihonEase",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>
          <Header />
          {children}
        </UserProvider>
      </body>
    </html>
  );
}
